name:                primus
version:             0.1.0.0
synopsis:            NonEmpty and positive functions
description:
  A library containing positive-valued and nonempty functions
  .
  Please see the README on GitHub at <https://github.com/gbwey/primus#readme>

homepage:            https://github.com/gbwey/primus#readme
license:             BSD3
author:              Grant Weyburne <gbwey9@gmail.com>
maintainer:          Grant Weyburne <gbwey9@gmail.com>
copyright:           2022 Grant Weyburne
category:            Data, General

github: gbwey/primus.git

dependencies:
- base >= 4.7 && < 5
- adjunctions
- deepseq
- distributive
- pos
- profunctors
- semigroupoids
- these

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wpartial-fields
  - -Wunused-type-patterns
  - -Wredundant-constraints
  - -Wmonomorphism-restriction
  - -Wmissing-deriving-strategies
  - -Wmissing-local-signatures
  - -Wmissing-export-lists
  - -Widentities

tests:
  primus-test:
    main:                Main.hs
    source-dirs:
    - test
    ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wpartial-fields
    - -Wunused-type-patterns
    - -Wredundant-constraints
    - -Wmissing-deriving-strategies
    - -Widentities
    - -Wno-missing-export-lists
    - -Wno-missing-local-signatures
    dependencies:
    - base
    - pos
    - primus
    - checkers
    - lens
    - QuickCheck
    - tasty
    - tasty-quickcheck
    - tasty-hunit
